### ISSUE TITLE
Font 'Lato' doesn't contain multiple foreign characters

### ISSUE THREAD

**Issue by mathias-erik** [Voog/design-berlin#35]
Berlin templates default font 'Lato' needs to be reviewed and upgraded. Currently there are multiple characters missing and thereby replaced with a different font. For example, these letters in Latvian:

![differences](https://cloud.githubusercontent.com/assets/6851355/9434715/3615cdb6-4a4a-11e5-9be7-d10dcb8895f5.jpg)

Background information:

Montserrat (headings) font doesn’t have Latvian glyphs in Google Font, it does however in Font Squirrel http://www.fontsquirrel.com/fonts/montserrat.

Lato does have Latin Extended in Google Fonts: https://www.google.com/fonts#UsePlace:use/Collection:Lato, also available in FS http://www.fontsquirrel.com/fonts/lato.

**Comment by runnel** [comment]
Kas see tähendab, et Google Fontsis on läti omad olemas või see Latin Extended ei ulartu läti omadeni?

**Comment by runnel** [comment]
Vaatasin, et Montserrat oleks keegi justkui upgradenud ka Lätit katma aasta tagasi. Palun vaadake üle.

**Comment by runnel** [comment]
http://www.fontsquirrel.com/fonts/montserrat

**Comment by sandissauka** [comment]
**Lato** does have Latin Extended in Google Fonts, but was not enabled in the theme.
Google Fonts https://www.google.com/fonts#UsePlace:use/Collection:Lato
It is also available in Font Squirrel http://www.fontsquirrel.com/fonts/lato

**Montseratt** (headings) font doesn’t have Latvian glyphs (Latin Extended) in Google Font, it does however in Font Squirrel http://www.fontsquirrel.com/fonts/montserrat.

**Comment by kaspar-naaber** [comment]
Thanks for pointing that out! :)

I will update the "Lato" font with Latin Extended from the Google Fonts and replace Montserrat with the Fontsquirrel version. These updates will fix the problem for new signups and for the sites that have standart (not customized) theme. Sandis, do you have any customized site that needs those updates aswell?

**Comment by sandissauka** [comment]
Thanks, Kaspar! I have a website with Berlin theme in development, but it does not have any customizations.

**Comment by kaspar-naaber** [comment]
When the button "customize" is clicked then the theme is treated as custom theme and will not be updated anymore. It doesn't matter if there are any modifications made in the code.

I updated your site manually – can you check if that helped?

**Comment by sandissauka** [comment]
Please check: http://www.mezaparkaskola.voog.com/biedriba. All the Latvian glyphs are substituted  with other (default?) font.










Although it seems I have a customized design and I cannot seem to switch to default.




Sandis

**Comment by kaspar-naaber** [comment]
It looks like you still managed to switch it back to default theme which is not updated yet. I did the modifications on your customized theme but switching back to default resetted the changes.

We will update the standard design today and then the fonts will be automatically fixed.

**Comment by martinsookael** [comment]
Hi guys! 
Googling Lato for Latvian comes here, must be a regional issue :). 

Experimenting with it around today and using 
<link type='text/css' rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700&subset=latin,latin-ext">

tends NOT to fix Lato for Latvian, some letters are still missing / with wrong font.

**Comment by kaspar-naaber** [comment]
Lato from Google Fonts indeed doesn't have all required characters for Latvian. Our Berlin template (and other templates) are using self-hosted "Lato" which was downloaded from Font Squirrel and it seems to work fine (http://www.fontsquirrel.com/fonts/lato).

@martinsookael – If you are using a Voog's template that uses Google hosted version of this font it's probably because you have set your page layout as "customized" in the past. After switching Voog's standard design to customized it will generate a copy of the layout code from the version that was live at that specific time and will not update the layout automattically anymore (to prevent owerwriting your custom code).

To receive all updates and latest version of the template you have to switch back to "standard" design, but please be aware that if you switch back you will lose all modifications that you have made in the template's code.
